### ISSUE TITLE
InvoiceForm: bugs

### ISSUE THREAD

**Issue by bossanova1986** [ovgu-ubit/output#156]

**Comment by bossanova1986** [comment]
invoice-form.component.ts:85  ERROR TypeError: Cannot set properties of undefined (setting 'dataSource')
    at Object.next (publication-form.component.ts:745:32)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at Subject.next (Subject.js:27:21)
    at DialogRef.close (dialog.mjs:393:27)
    at MatDialogRef._finishDialogClose (dialog.mjs:455:19)
    at Object.next (dialog.mjs:343:18)

**Comment by bossanova1986** [comment]
ERROR TypeError: Cannot read properties of undefined (reading 'label')
    at InvoiceFormComponent_td_44_Template (invoice-form.component.html:56:57)
    at executeTemplate (core.mjs:12003:13)
    at refreshView (core.mjs:13498:13)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInEmbeddedViews (core.mjs:13606:13)
    at refreshView (core.mjs:13522:9)
    at detectChangesInView (core.mjs:13663:9)
    at detectChangesInComponent (core.mjs:13638:5)
    at detectChangesInChildComponents (core.mjs:13676:9)
    at refreshView (core.mjs:13548:13)

**Comment by bossanova1986** [comment]
still a bug that cost items are erased if canceled
