### ISSUE TITLE
OA-Category cannot be deleted => optional reset all references to NULL

### ISSUE THREAD

**Issue by bossanova1986** [ovgu-ubit/output#177]
ERROR [ExceptionsHandler] update or delete on table "oa_category" violates foreign key constraint "FK_2890e02be3bb889ccd94cc9cd9d" on table "publication"
4|output2  | QueryFailedError: update or delete on table "oa_category" violates foreign key constraint "FK_2890e02be3bb889ccd94cc9cd9d" on table "publication"
4|output2  |     at PostgresQueryRunner.query (/home/boss/projects/node.js/output2/output-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
4|output2  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
4|output2  |     at async DeleteQueryBuilder.execute (/home/boss/projects/node.js/output2/output-api/node_modules/typeorm/query-builder/DeleteQueryBuilder.js:52:33)
4|output2  |     at async OACategoryService.delete (/home/boss/projects/node.js/output2/output-api/dist/output-api/src/services/entities/oa-category.service.js:121:16)
4|output2  |     at async /home/boss/projects/node.js/output2/output-api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
4|output2  |     at async /home/boss/projects/node.js/output2/output-api/node_modules/@nestjs/core/router/router-proxy.js:9:17

**Comment by bossanova1986** [comment]
still references to this category in soft deletes.... option to reset all references to NULL

**Comment by bossanova1986** [comment]
is already done, was just extended to soft deleted pubs
