### ISSUE TITLE
PublicationForm: Identifier cannot be added

### ISSUE THREAD

**Issue by bossanova1986** [ovgu-ubit/output#184]
TypeError: Cannot read properties of undefined (reading 'push')
    at PublicationFormComponent.addId (publication-form.component.ts:746:26)
    at PublicationFormComponent_Template_button_click_41_listener (publication-form.component.html:80:74)
    at executeListenerWithErrorHandling (core.mjs:16795:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:16828:22)
    at HTMLButtonElement.<anonymous> (platform-browser.mjs:665:17)
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:10757:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:11070:33)

**Comment by bossanova1986** [comment]
solved by 445d089
