### ISSUE TITLE
Bugfixing

### ISSUE THREAD

**Issue by bossanova1986** [ovgu-ubit/output#88]
- [x] if backend is not reachable, there should be an error

**Comment by bossanova1986** [comment]
- [ ] Export: if filter is selected but none is there, backend gets an error 
 at MasterExportService.export (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\services\export\master-export.service.ts:31:64)
    at ExportController.exportMaster (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\controller\ExportController.ts:81:42)

**Comment by bossanova1986** [comment]
- [ ] BASE import hanging at 100.2% for 2023 with update

2024-03-20 08:01:28.452 [info] @ BASE: Starting import with parameters func: PerformSearch; query: (magdeburg+OR+ovgu+OR+guericke)+and+dcyear:2023; format: json
2024-03-20 08:01:28.453 [info] @ BASE: 1035 elements found

**Comment by bossanova1986** [comment]
- [ ] check error

2024-03-20 08:08:01.350 [error] @ mapUpdate: QueryFailedError: Wert »286000000000000000000« ist außerhalb des gültigen Bereichs für Typ integer
at PostgresQueryRunner.query (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\driver\postgres\PostgresQueryRunner.ts:299:19)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at UpdateQueryBuilder.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\query-builder\UpdateQueryBuilder.ts:145:33)
at updateSubject (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\SubjectExecutor.ts:617:38)
at async Promise.all (index 0)
at SubjectExecutor.executeUpdateOperations (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\SubjectExecutor.ts:668:9)
at SubjectExecutor.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\SubjectExecutor.ts:148:9)
at EntityPersistExecutor.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\EntityPersistExecutor.ts:182:21)
at OpenAlexImportService.mapUpdate (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\services\import\abstract-import.ts:708:41)
at Object.next (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\services\import\api-import-offset.service.ts:169:42) - ID 1070

**Comment by bossanova1986** [comment]
- [ ] unpaywall does not fill best oa license

**Comment by bossanova1986** [comment]
- [ ] Plausibility duplicates: should also compare string length not just includes ("Methoden" in "Methoden der....")

**Comment by bossanova1986** [comment]
- [ ] remove console logs in backend

**Comment by bossanova1986** [comment]
- [ ] 2024-03-20 13:15:54.041 [error] @ mapUpdate: QueryFailedError: null value in column "status" violates not-null constraint
at PostgresQueryRunner.query (/home/boss/projects/node.js/output2/output-api/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async UpdateQueryBuilder.execute (/home/boss/projects/node.js/output2/output-api/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
at async updateSubject (/home/boss/projects/node.js/output2/output-api/node_modules/typeorm/persistence/SubjectExecutor.js:380:38)
at async Promise.all (index 0)

**Comment by bossanova1986** [comment]
- [ ] hide X in author inst view if read-only

**Comment by bossanova1986** [comment]
- [ ] POST greater entity
QueryFailedError: ungültige Eingabesyntax für Typ timestamp with time zone: »«
    at PostgresQueryRunner.query (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\driver\postgres\PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at InsertQueryBuilder.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\query-builder\InsertQueryBuilder.ts:163:33)
    at SubjectExecutor.executeInsertOperations (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\SubjectExecutor.ts:434:42)
    at SubjectExecutor.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\SubjectExecutor.ts:137:9)
    at EntityPersistExecutor.execute (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\persistence\EntityPersistExecutor.ts:182:21)
    at GreaterEntityService.save (C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\src\services\entities\greater-entitiy.service.ts:28:16)
    at C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at C:\Users\sbosse\eclipse-workspace\GitHub\output\output-api\node_modules\@nestjs\core\router\router-proxy.js:9:17
